-- TODO: Uriel to create relevant tables
-- TODO: create triggers and procedures

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS airflow;

CREATE TABLE IF NOT EXISTS api.summoner_info (
    puuid TEXT PRIMARY KEY,
    game_name TEXT,
    tag_line TEXT,
    region TEXT,
    sub_region TEXT
);

CREATE TABLE IF NOT EXISTS api.match_id (
    matchId TEXT PRIMARY KEY,
    puuid TEXT REFERENCES api.summoner_info(puuid)
);

CREATE TABLE IF NOT EXISTS api.challenge (
    challengeId SERIAL PRIMARY KEY,
    twelveAssistStreakCount INTEGER,
    HealFromMapSources DOUBLE PRECISION,
    InfernalScalePickup INTEGER,
    SWARM_DefeatAatrox INTEGER,
    SWARM_DefeatBriar INTEGER,
    SWARM_DefeatMiniBosses INTEGER,
    SWARM_EvolveWeapon INTEGER,
    SWARM_Have3Passives INTEGER,
    SWARM_KillEnemy INTEGER,
    SWARM_PickupGold INTEGER,
    SWARM_ReachLevel50 INTEGER,
    SWARM_Survive15Min INTEGER,
    SWARM_WinWith5EvolvedWeapons INTEGER,
    abilityUses INTEGER,
    acesBefore15Minutes INTEGER,
    alliedJungleMonsterKills INTEGER,
    baronTakedowns INTEGER,
    blastConeOppositeOpponentCount INTEGER,
    bountyGold INTEGER,
    buffsStolen INTEGER,
    completeSupportQuestINTEGERime INTEGER,
    controlWardsPlaced INTEGER,
    damagePerMinute DOUBLE PRECISION,
    damageTakenOnTeamPercentage DOUBLE PRECISION,
    dancedWithRiftHerald INTEGER,
    deathsByEnemyChamps INTEGER,
    dodgeSkillShotsSmallWindow INTEGER,
    doubleAces INTEGER,
    dragonTakedowns INTEGER,
    effectiveHealAndShielding DOUBLE PRECISION,
    elderDragonKillsWithOpposingSoul INTEGER,
    elderDragonMultikills INTEGER,
    enemyChampionImmobilizations INTEGER,
    enemyJungleMonsterKills INTEGER,
    epicMonsterKillsNearEnemyJungler INTEGER,
    epicMonsterKillsWithin30SecondsOfSpawn INTEGER,
    epicMonsterSteals INTEGER,
    epicMonsterStolenWithoutSmite INTEGER,
    firstTurretKilled INTEGER,
    fistBumpParticipation INTEGER,
    flawlessAces INTEGER,
    fullTeamTakedown INTEGER,
    gameLength DOUBLE PRECISION,
    getTakedownsInAllLanesEarlyJungleAsLaner INTEGER,
    goldPerMinute DOUBLE PRECISION,
    hadOpenNexus INTEGER,
    highestCrowdControlScore INTEGER,
    immobilizeAndKillWithAlly INTEGER,
    initialBuffCount INTEGER,
    initialCrabCount INTEGER,
    jungleCsBefore10Minutes INTEGER,
    junglerTakedownsNearDamagedEpicMonster INTEGER,
    kTurretsDestroyedBeforePlatesFall INTEGER,
    kda DOUBLE PRECISION,
    killAfterHiddenWithAlly INTEGER,
    killParticipation DOUBLE PRECISION,
    killedChampTookFullTeamDamageSurvived INTEGER,
    killingSprees INTEGER,
    killsNearEnemyTurret INTEGER,
    killsOnOtherLanesEarlyJungleAsLaner INTEGER,
    killsOnRecentlyHealedByAramPack INTEGER,
    killsUnderOwnTurret INTEGER,
    killsWithHelpFromEpicMonster INTEGER,
    knockEnemyINTEGERoTeamAndKill INTEGER,
    landSkillShotsEarlyGame INTEGER,
    laneMinionsFirst10Minutes INTEGER,
    legendaryCount INTEGER,
    legendaryItemUsed INTEGER[],
    lostAnInhibitor INTEGER,
    maxKillDeficit INTEGER,
    mejaisFullStackINTEGERime INTEGER,
    moreEnemyJungleThanOpponent INTEGER,
    multiKillOneSpell INTEGER,
    multiTurretRiftHeraldCount INTEGER,
    multikills INTEGER,
    multikillsAfterAggressiveFlash INTEGER,
    outerTurretExecutesBefore10Minutes INTEGER,
    outnumberedKills INTEGER,
    outnumberedNexusKill INTEGER,
    perfectDragonSoulsTaken INTEGER,
    perfectGame INTEGER,
    pickKillWithAlly INTEGER,
    poroExplosions INTEGER,
    quickCleanse INTEGER,
    quickFirstTurret INTEGER,
    quickSoloKills INTEGER,
    riftHeraldTakedowns INTEGER,
    saveAllyFromDeath INTEGER,
    scuttleCrabKills INTEGER,
    shortestTimeToAceFromFirstTakedown DOUBLE PRECISION,
    skillshotsDodged INTEGER,
    skillshotsHit INTEGER,
    snowballsHit INTEGER,
    soloBaronKills INTEGER,
    soloKills INTEGER,
    stealthWardsPlaced INTEGER,
    survivedSingleDigitHpCount INTEGER,
    survivedThreeImmobilizesInFight INTEGER,
    takedownOnFirstTurret INTEGER,
    takedowns INTEGER,
    takedownsAfterGainingLevelAdvantage INTEGER,
    takedownsBeforeJungleMinionSpawn INTEGER,
    takedownsFirstXMinutes INTEGER,
    takedownsInAlcove INTEGER,
    takedownsInEnemyFountain INTEGER,
    teamBaronKills INTEGER,
    teamDamagePercentage INTEGER,
    teamElderDragonKills INTEGER,
    teamRiftHeraldKills INTEGER,
    tookLargeDamageSurvived INTEGER,
    turretPlatesTaken INTEGER,
    turretTakedowns INTEGER,
    turretsTakenWithRiftHerald INTEGER,
    twentyMinionsIn3SecondsCount INTEGER,
    twoWardsOneSweeperCount INTEGER,
    unseenRecalls INTEGER,
    visionScorePerMinute INTEGER,
    voidMonsterKill INTEGER,
    wardTakedowns INTEGER,
    wardTakedownsBefore20M INTEGER,
    wardsGuarded INTEGER
);

CREATE TABLE IF NOT EXISTS api.participant (
    PlayerScore0 INTEGER,
    PlayerScore1 INTEGER,
    PlayerScore2 INTEGER,
    PlayerScore3 INTEGER,
    PlayerScore4 INTEGER,
    PlayerScore5 INTEGER,
    PlayerScore6 INTEGER,
    PlayerScore7 INTEGER,
    PlayerScore8 INTEGER,
    PlayerScore9 INTEGER,
    allInPings INTEGER,
    assistMePings INTEGER,
    assists INTEGER,
    baronKills INTEGER,
    basicPings INTEGER,
    challenges INTEGER[], -- REFERENCES challenge(challengeId),
    champExperience INTEGER,
    champLevel INTEGER,
    championId INTEGER,
    championName INTEGER,
    commandPings INTEGER,
    consumablesPurchased INTEGER,
    damageDealtToBuildings DOUBLE PRECISION,
    damageDealtToObjectives DOUBLE PRECISION,
    damageDealtToTurrets DOUBLE PRECISION,
    damageSelfMitigated INTEGER,
    dangerPings INTEGER,
    deaths INTEGER,
    detectorWardsPlaced INTEGER,
    doubleKills INTEGER,
    dragonKills INTEGER,
    eligibleForProgression BOOLEAN,
    enemyMissingPings INTEGER,
    enemyVisionPings INTEGER,
    firstBloodAssist BOOLEAN,
    firstBloodKill BOOLEAN,
    firstTowerAssist BOOLEAN,
    firstTowerKill BOOLEAN,
    gameEndedInEarlySurrender BOOLEAN,
    gameEndedInSurrender BOOLEAN,
    getBackPings INTEGER,
    goldEarned INTEGER,
    goldSpent INTEGER,
    holdPings INTEGER,
    individualPosition TEXT,
    inhibitorKills INTEGER,
    inhibitorTakedowns INTEGER,
    inhibitorsLost INTEGER,
    item0 INTEGER,
    item1 INTEGER,
    item2 INTEGER,
    item3 INTEGER,
    item4 INTEGER,
    item5 INTEGER,
    item6 INTEGER,
    itemsPurchased INTEGER,
    killingSprees INTEGER,
    kills INTEGER,
    lane TEXT,
    largestCriticalStrike INTEGER,
    largestKillingSpree INTEGER,
    largestMultiKill INTEGER,
    longestTimeSpentLiving INTEGER,
    magicDamageDealt INTEGER,
    magicDamageDealtToChampions INTEGER,
    magicDamageTaken INTEGER,
    physicalDamageDealt INTEGER,
    physicalDamageDealtToChampions INTEGER,
    physicalDamageTaken INTEGER,
    placement INTEGER,
    playerAugment1 INTEGER,
    playerAugment2 INTEGER,
    playerAugment3 INTEGER,
    playerAugment4 INTEGER,
    playerAugment5 INTEGER,
    playerAugment6 INTEGER,
    playerSubteamId INTEGER,
    profileIcon INTEGER,
    pushPings INTEGER,
    puuid TEXT REFERENCES api.summoner_info(puuid),
    quadraKills INTEGER,
    retreatPings INTEGER,
    role TEXT,
    sightWardsBoughtInGame INTEGER,
    spell1Casts INTEGER,
    spell2Casts INTEGER,
    spell3Casts INTEGER,
    spell4Casts INTEGER,
    subteamPlacement INTEGER,
    summoner1Casts INTEGER,
    summoner1Id INTEGER,
    summoner2Casts INTEGER,
    summoner2Id INTEGER,
    summonerId TEXT,
    summonerLevel INTEGER,
    summonerName TEXT,
    teamEarlySurrendered BOOLEAN,
    teamId INTEGER,
    teamPosition INTEGER,
    timeCCingOthers INTEGER,
    timePlayed INTEGER,
    totalAllyJungleMinionsKilled INTEGER,
    totalDamageDealt INTEGER,
    totalDamageDealtToChampions INTEGER,
    totalDamageShieldedOnTeammates INTEGER,
    totalDamageTaken INTEGER,
    totalEnemyJungleMinionsKilled INTEGER,
    totalHeal INTEGER,
    totalHealsOnTeammates INTEGER,
    totalMinionsKilled INTEGER,
    totalTimeCCDealt INTEGER,
    totalTimeSpentDead INTEGER,
    totalUnitsHealed INTEGER,
    tripleKills INTEGER,
    trueDamageDealt INTEGER,
    trueDamageDealtToChampions INTEGER,
    trueDamageTaken INTEGER,
    turretKills INTEGER,
    turretTakedowns INTEGER,
    turretsLost INTEGER,
    unrealKills INTEGER,
    visionClearedPings INTEGER,
    visionScore INTEGER,
    visionWardsBoughtInGame INTEGER,
    wardsKilled INTEGER,
    wardsPlaced INTEGER,
    win BOOLEAN
);

CREATE TABLE IF NOT EXISTS api.match_info (
    matchId TEXT PRIMARY KEY,
    endOfGameResult TEXT,
    gameCreation BIGINT,
    gameDuration BIGINT,
    gameEndTimestamp BIGINT,
    gameId BIGINT,
    gameMode TEXT,
    gameName TEXT,
    gameStartTimestamp BIGINT,
    gameType TEXT,
    gameVersion TEXT,
    mapId INTEGER,
    participants TEXT[], -- REFERENCES participant(puuid),
    platformId TEXT,
    queueId INTEGER,
    tournamentCode TEXT
);
